### ISSUE TITLE
PayMill gateway

### ISSUE THREAD

**Issue by stefanozoffoli** [thephpleague/omnipay#15]
Hi,

kudos for this library!

Could you add PayMill gateway to your to-do list?

https://www.paymill.com/

Their apis are very similar to stripe.

Thank you!

**Comment by gour** [comment]
Any news in regard to the status of PayMill support in OmniPay?

**Comment by judgej** [comment]
@gour A link to https://github.com/bramdevries/omnipay-paymill was posted. That's the Paymill support that we know of. Have you tried that?
