### ISSUE TITLE
Braintree Gateway and Symfony2 integration

### ISSUE THREAD

**Issue by pjedrzejewski** [thephpleague/omnipay#16]
Hey!

I'm in progress of implementing [Braintree](https://www.braintreepayments.com/) gateway.
So if anything should stop me (you have it in works too), please let me know! :smile: 

As you probably know from @stloyd, we have started some work on Symfony2 integration, I hope to have initial working version by the end of the weekend, but this is just a rough estimation - I'll do my best. You can track the progress [here](https://github.com/Sylius/SyliusPaymentsBundle/tree/feature/di).

I'll probably split this into 2 bundles, one for just **Omnipay** integration.
And second with more Sylius-specific features.

Thanks for your work!

Bests,
Pawel

**Comment by DanPhyxius** [comment]
Hi @pjedrzejewski,

is anyone working (or maybe, it's done) on Braintree integration for Sylius?

I need that for a customer so i would like to understand if i have to make it from myself! :)

Thanks a lot,
Dan
