### ISSUE TITLE
skrill no completePurchase?

### ISSUE THREAD

**Issue by ghost** [thephpleague/omnipay#183]
when i use skrill,there is no completePurchase,so i don't konw is it real pay.
i find maybe need use 

```
$q =  $this->gateway
                ->transfer($this->par)->send();  
    //  $q = $q->getTransactionReference();
```

but need sesssionID,so .how can i do?
thank you

**Comment by nikunj05** [comment]
@alfaproject : How can we use completePurchase() ? Do we have to call purchase() first ? I would like to get response data as mentioned in StatusCallback.php
