### ISSUE TITLE
omnipay 1.1 issue: paypal is confused about currencies

### ISSUE THREAD

**Issue by sunnysideup** [thephpleague/omnipay#188]
Hi

I am using https://github.com/burnbright/silverstripe-omnipay.  All is working well, but I can not pay with paypal and I get this funny message:

The transaction currency specified must be the same as previously specified.

I am not sure where the error is.  Any ideas on how to debug this???

**Comment by Bulmer** [comment]
I am having the exact same problem. Should I pass 'currency' => 'AUD' explicitly in the purchase() call?
I just need to confirm this first as I have a live website and want to avoid any more problems. Cheers.

**Comment by cfreear** [comment]
Some gateways that do auth/purchase > complete style flows require you to specify the transaction data in both calls (including currency/amount etc.) It sounds like you might be specifying AUD in the initial call but not in the 'complete' call and the library is defaulting...
