### ISSUE TITLE
Update Packagist references to the new URL

### ISSUE THREAD

**Issue by raphael-riel** [thephpleague/omnipay#201]
Since Sept. 06, when github links were changed, composer can't fetch omnipay and omnipay-*.

Links in Packagist.org weren't changed accordingly.

**Comment by hackalot805** [comment]
Auth.net announced new URLs... https://api2.authorize.net/xml/v1/request.api and others... do yo have an ETA for omnipay using these new URLs?  Thanks!

**Comment by judgej** [comment]
@hackalot805 You might want to [follow this ticket](https://github.com/thephpleague/omnipay-authorizenet/issues/24). I'm personally up to me neck in stuff for the next week, so am unlikely going to get a chance to look at it.
