### ISSUE TITLE
Retrieve original transactionId after completePurchase()

### ISSUE THREAD

**Issue by hellopablo** [thephpleague/omnipay#204]
Hello,

I'm looking for an abstracted way to retrieve the original transaction ID when dealing with the callback (in this case, from WorldPay). I've come across [this SO question](http://stackoverflow.com/questions/21257810/omnipay-how-to-retrieve-original-transaction-id-when-using-worldpay-callback), but I'm in agreement with [the comment](http://stackoverflow.com/questions/21257810/omnipay-how-to-retrieve-original-transaction-id-when-using-worldpay-callback#comment40448432_21293325) on Adrian's answer - surely it makes sense that there be a way to do this in Omnipay!

I'm no expert (at all) in any of the gateways, and maybe I'm wrong, but I'd assume that each gateway offers the ability to return the transaction ID. for Worldpay this could be the cartId, PayPal could use the invoice ID field, etc.

I've looked through the source and I'm 99.9% positive this isn't implemented. Before I roll my own attempt to get the ID (i.e in my own code switch the Gateway and manually retrieve the relevant piece of info from the POST array or whatever), **I'm wondering if there's something on the roadmap, or if there's a sensible approach I can use** (Adrian's response on SO is too convoluted IMO, I'd rather just query $_POST['cartId']...?). 

Thanks!

**Comment by abdrasulov** [comment]
I've faced the same issue. The suggested solution didn't work for me, since the transactionRef is null when the response is redirect. I totally agree with @hellopablo. Retrieving the transactionId from the gateway response would be the best solution.

**Comment by judgej** [comment]
I certainly try to make both transaction ID and Reference available in the complete* and Notify classes where possible. It seems that gateways vary so wildly, that some gateways will support one, or the other, or both.

I think for now, raise this individually with the gateway drivers that *could* support either but don't.

Also we should stop seconding fields such as invoice for holding the local transaction id. Filed like that have their own specific purpose.
