### ISSUE TITLE
Is anyone working on a Braintree module?

### ISSUE THREAD

**Issue by lfjeff** [thephpleague/omnipay#211]
I've seen Braintree mentioned a few times, but is anyone working on developing an Omnipay module?

We're currently using Payflow, but plan to switch to Braintree.

If someone has already done some work on Braintree, I would hate to reinvent the wheel. 

Even if your code is not complete, I would be happy to collaborate and help you to finish it.

**Comment by dhalarewich** [comment]
Just throwing my name in the hat. We (LemonStand) may tackle this in the coming weeks as well.

**Comment by platowski** [comment]
I'm just about to test this solution https://bitbucket.org/temando-ondemand/omnipay-braintree.

**Comment by kayladnls** [comment]
@platowski There's some good work done there, and thank you. It does deviate quite heavily from the other Omnipay gateways in the way you're using transactions, configuration entities etc. Can you walk me through some of the reasoning of building it that way?

**Comment by kayladnls** [comment]
With the number of people in this thread and elsewhere that have mentioned wanting to work on a braintree gateway for Omnipay, I've been strongly considering setting up a base repo with some early scaffolding that we can start PRing against. 

Thoughts for or against that?

**Comment by platowski** [comment]
@kayladnls This is someone's repo that I just found, so unfortunately I can not speak for the author. Currently I'm on research stage so I'm comparing other developers approaches to avoid reinventing the wheel. Braintree SDK for PHP is quite nicely done so majority of implementations that I saw was just a SF2/other frameworks wrappers like this https://github.com/excelwebzone/EWZBraintreeBundle. I'm not sure at this point, but what I understood so far, that can be a problem to do it exactly in Omnipay way due to how BT PHP sdk is using JS components to prepare valid transaction.

**Comment by vinkla** [comment]
@kayladnls This is definitely wanted by the community. Plus one on setting up a base repo.

**Comment by kayladnls** [comment]
Very barebones repo set up: https://github.com/thephpleague/omnipay-braintree

I'll get some actual code and tests in their shortly.

**Comment by vinkla** [comment]
@kayladnls nice!

**Comment by lfjeff** [comment]
Are you planning to
 recreate everything from scratch or do you
 intend to create a "wrapper" that provides
 an Omnipay-style interface to the existing
 Braintree PHP library?
 
 
 >>  Very
 barebones repo set up: >>
   https://github.com/thephpleague/omnipay-braintree
  >>  I'll get some actual
 code and tests in their shortly.   >>
  Reply to this email directly or view
 it on GitHub.  >>   

----------------------- Original
 Message -----------------------

**Comment by kayladnls** [comment]
@lfjeff i'm very not happy when their current PHP SDK, so I would likely hand write it.

**Comment by lfjeff** [comment]
Good luck.  That was my original
 plan, but we needed to get things working
 quickly and I didn't have time to completely
 reimplement everything.
 
Doing the basic stuff (auth, settlement,
 void, etc) might not be too bad.  However,
 we needed to use submerchants and a lot of
 their specialized features that do not cleanly
 map to Omnipay.
 
After you check-in your initial
 efforts, I'll take a look and may be able
 to help.
 
 
 >>  @lfjeff
 i'm very not happy when their current PHP
 SDK, so I would likely >>
   hand write it.   >>
  Reply to this email directly or view
 it on GitHub.  >>   

----------------------- Original
 Message -----------------------

**Comment by frikken** [comment]
Hi kayladnls,
omnipay seems great but I need also Braintree . . . have you some update?

Thanks

**Comment by kayladnls** [comment]
@frikken I've been slammed recently with work and homelife. It's still on the agenda, but I haven't had the time yet.

**Comment by coatesap** [comment]
I'll also be needing a Braintree driver shortly, but it looks like this repo may be under active development https://github.com/sproutstudioinc/omnipay-braintree, so it might be worth trying to adopt that one as the 'official' driver...

**Comment by barryvdh** [comment]
I'm also gonna build one soon, but only using the `paymentMethodNonce` billing, not the actual card data.

**Comment by barryvdh** [comment]
I've created a rough start using the payment nonce.

@kayladnls or @philsturgeon can you add `omnipay-braintree` to the Omnipay organisation so I can push it?

**Comment by coatesap** [comment]
@barryvdh I've only just started looking at what integration options Braintree provide, but the nonce method does look like the right way to go in order to avoid potential PCI issues. I didn't spot that the repo that I linked to wasn't using this, so happy to collaborate on the driver.

**Comment by ChrisFrench** [comment]
I started down the road of omnipay and left it because I wanted a tighter
integation, but I expect on a simple level it could be done.

**Comment by judgej** [comment]
@ChrisFrench OmniPay only handles the messaging. The integration around that - routes, controllers, storage - are up to you, and can be as "tight" as you like. You can't tell an integration is based on OmniPay from the outside.

**Comment by kayladnls** [comment]
@barryvdh it's added.

**Comment by barryvdh** [comment]
Okay, initial basic implementation is on https://github.com/thephpleague/omnipay-braintree :)

**Comment by lfjeff** [comment]
It appears that your implementation
 is built on top of the Braintree SDK, which
 seems to be against the Omnipay philosophy:
 
"There are no dependencies on official
 payment gateway PHP packages - we prefer
 to work with the HTTP API directly. Under
 the hood, we use the popular and powerful
 Guzzle
 library to make HTTP requests."
 
Personally, I have no problems with
 this.  I had considered doing this
 myself since re-implementing the low-level
 interface for all the Braintree functions
 appears to be a daunting task.
 
Unless it creates problems, I'd rather
 have something that works now, instead of
 waiting for a "pure" package that is built
 from from scratch.  However, since it
 is an exception to the "rules" you may want
 to mention the Braintree library dependency
 in the documentation.  If someone else
 is really motivated, maybe they can refactor
 the code later and remove the Braintree SDK
 dependency.
 
 >>  Okay,
 initial basic implementation is on >>
   https://github.com/thephpleague/omnipay-braintree
 :)  >>  Reply to
 this email directly or view it on GitHub.
  >>   

----------------------- Original
 Message -----------------------
  
From: "Barry vd. Heuvel"
 <notifications@github.com>
To: thephpleague/omnipay
 <omnipay@noreply.github.com>
Date: Tue, 07 Jul 2015 02:16:59
 -0700
Subject: Re: [omnipay] Is
 anyone working on a Braintree module? (#211)
  
Okay, initial basic implementation is
 on https://github.com/thephpleague/omnipay-braintree
 :)
—Reply
 to this email directly or view
 it on GitHub.

**Comment by barryvdh** [comment]
Yeah, but I don't think the HTTP API is really exposed. They are just offering their PHP (or other languages) SDK libraries, not their REST API. 
See https://www.braintreepayments.com/blog/when-rest-isnt-good-enough/ (didn't find a recent update)

If they only officially support the SDKs, it could be dangerous to use undocumented API's by reverse engineering the php library. Plus it would be very time consuming.

Don't know what the exact considerations are, but it probably won't be a big problem. Only the testing part will be different from other API's, because we'd have to fake the SDK responses etc.

**Comment by lfjeff** [comment]
Makes sense to me.  If Braintree
 only offers official support via their SDK,
 then that's what we should use.
 
Currently we're using a kludgy home-grown
 interface on top of the Braintree SDK, so
 it would be nice to have a consistent Omnipay
 interface.  We use a lot of special
 Braintree functions (like escrow, submerchants,
 etc) that aren't provided by most processors,
 so someone will need to figure out how to
 map those to Omnipay methods.  If I
 have some time, maybe I can work on that
 and help out.
 
>>  Yeah,
 but I don't think the HTTP API is really
 exposed. They are just >>
   offering their PHP (or other
 languages) SDK libraries, not their REST >>
   API.  >>   See
 https://www.braintreepayments.com/blog/when-rest-isnt-good-enough/ >>
   (didn't find a recent update)
  >>  If they only officially
 support the SDKs, it could be dangerous to
 use >>   undocumented
 API's by reverse engineering the php library.
 Plus it would >>   be
 very time consuming.  >>  Don't
 know what the exact considerations are, but
 it probably won't be a >>
   big problem. Only the testing
 part will be different from other API's, >>
   because we'd have to fake the
 SDK responses etc.  >>
  Reply to this email directly or view
 it on GitHub.  >>   

----------------------- Original
 Message -----------------------
  
From: "Barry vd. Heuvel"
 <notifications@github.com>
To: thephpleague/omnipay
 <omnipay@noreply.github.com>
Date: Tue, 07 Jul 2015 12:22:55
 -0700
Subject: Re: [omnipay] Is
 anyone working on a Braintree module? (#211)
  
Yeah, but I don't think the HTTP API is
 really exposed. They are just offering their
 PHP (or other languages) SDK libraries, not
 their REST API. See https://www.braintreepayments.com/blog/when-rest-isnt-good-enough/
 (didn't find a recent update)
If they only officially support the SDKs,
 it could be dangerous to use undocumented
 API's by reverse engineering the php library.
 Plus it would be very time consuming.
Don't know what the exact considerations
 are, but it probably won't be a big problem.
 Only the testing part will be different from
 other API's, because we'd have to fake the
 SDK responses etc.
—Reply
 to this email directly or view
 it on GitHub.
