### ISSUE TITLE
Sage pay repeat billing

### ISSUE THREAD

**Issue by bweston92** [thephpleague/omnipay#213]
Great package, I love it but in relation to #208 the docs aren't really that explicit.

Is token billing repeat payments? and if so how to use it with Sage Pay? Surly there is some more documentation that this read me...

**Comment by judgej** [comment]
@bweston92 There is an addition to the Sage Pay driver to add repeat billing, that is just going through now. Sage Pay repeat billing allows a new payment or authorisation to be created based on a past payment. There is no card token involved, but so long as you have the `transactionReference` for the previous successful payment, then a new payment can be made against it.

That's just going into the master branch over the next few days, and may give you what you need.
