### ISSUE TITLE
[request] Ogone gateway

### ISSUE THREAD

**Issue by jaoued** [thephpleague/omnipay#220]
Hi,

Can you add [Ogone](http://payment-services.ingenico.com/gb/en) gateway ?

Useful url: https://github.com/ETSGlobal/ETSPaymentOgoneBundle

Regards.

**Comment by dschallert** [comment]
Hi there,
we're currently adopting Ogone for omnipay. I'll post an updated comment with the repo url when its done. Should be within the next 2-3 weeks.

Thanks
Dominic

**Comment by kayladnls** [comment]
@dschallert feel free to open a PR to add Ogone to the list of 3rd party gateways when it's done. I'd be happy to include it.
