### ISSUE TITLE
"Card Present" implementation?

### ISSUE THREAD

**Issue by acicali** [thephpleague/omnipay#229]
Some payment gateways support "card present" transactions, where the actual track data is submitted. This usually decreases processing fees because there tends to be a lower risk of fraud. Are there any plans to support this type of transaction with Omnipay?

Thanks to all of the contributors for the hard work put into this wonderful package.

**Comment by kayladnls** [comment]
Do you have an example API I can look at?

**Comment by acicali** [comment]
Here's the actual Authorize.net documentation: http://www.authorize.net/support/CP_guide.pdf

Specifically, page 16.  It appears that Authorize.net AIM allows the entire track1 or track2 data in lieu of the card number and expiration date.  Probably this would all be handled within the CreditCard object?

I'm not sure of all the other processors though, if this is something common.

**Comment by acicali** [comment]
I tried to find another gateway in the Omnipay list that also supported this, but couldn't. Maybe Authorize.net is the only one after all.

**Comment by kayladnls** [comment]
If Authorize.net is the only gateway that supports it, it likely won't be added as a feature. If more gateways start offering that as a service, I'd be happy to implement it.

**Comment by acicali** [comment]
Makes sense.  Thank you.

**Comment by slogsdon** [comment]
FWIW, Heartland Payment Systems supports Card Present transactions through its gateway as well, both unencrypted and encrypted. It also supports the tokenization of track data client-side.

I'm looking to implement an Omnipay package in the near future, and it'd be great to offer Card Present along with Card Not Present.
