### ISSUE TITLE
Authorization with redirect example available.

### ISSUE THREAD

**Issue by 3even** [thephpleague/omnipay#231]
Is there an authorization with redirect example available?
This following does not seem to work

```
$formData = [
    'number' => '4242424242424242',
    'expiryMonth' => '6',
    'expiryYear' => '2016',
    'cvv' => '123'
];

$response = $gateway->authorize([
    'amount' => '10.00',
    'card' => $formData,
    'returnUrl' => 'https://www.example.com/return',
    'cancelUrl' => 'https://www.example.com/cancel'
])->send();

```
Based on the documentation this should authorize the amount only however it does a capture instead. 
http://omnipay.thephpleague.com/api/authorizing/

**Comment by cfreear** [comment]
Which gateway are you using? That looks like a Stripe test card number but Stripe doesn't support a return/cancelurl as there is no offsite/redirect method like there is with paypal.

**Comment by kayladnls** [comment]
@3even are you still having problems with this?

**Comment by 3even** [comment]
@kayladnls I was able to sort myself out thanks.

If anyone is interested this is the code I used to successfully authorize a transaction via PayPal Express.

```
        $params = [
            'amount'    => '10.00',
            'currency'  => 'USD'
            'cancelUrl' => 'https://www.example.com/cancel',
            'returnUrl' => 'https://www.example.com/return'
        ];


        $response = $gateway->authorize($params)->send();

        if ($response->isSuccessful()) {
            
            // payment was successful: update database

        } elseif ($response->isRedirect()) {
            
            // redirect to offsite payment gateway
            $response->redirect();
        
        } else {
            
            // payment failed: display message to customer
        
        }
```

**Comment by devnix** [comment]
Hi @3even! It's been a while since you closed this issue but, could you sketch what we should catch on the cancel/return URLs? I'm *very* nagged because of the lack of documentation...
