### ISSUE TITLE
guzzle/guzzle is recommended

### ISSUE THREAD

**Issue by evgenius** [thephpleague/omnipay#235]
That's what I see when installing dependencies using `composer install`:

> Package guzzle/common is abandoned, you should avoid using it. Use guzzle/guzzle instead.
Package guzzle/stream is abandoned, you should avoid using it. Use guzzle/guzzle instead.
Package guzzle/parser is abandoned, you should avoid using it. Use guzzle/guzzle instead.
Package guzzle/http is abandoned, you should avoid using it. Use guzzle/guzzle instead.
Package guzzle/plugin-mock is abandoned, you should avoid using it. Use guzzle/guzzle instead.

**Comment by barryvdh** [comment]
Guzzle/http is just a subtree split from guzzle/guzzle so I guess we could just use guzzle/guzzle, but that would pull in a larger package. Probably not a big deal, but curious why it's deprecated.

**Comment by evgenius** [comment]
@barryvdh Yeah, I realize it's a bigger package. I'm new to omnipay and guzzle so if someone could find out the reason why it's deprecated it'd be great. I can do it myself at the weekend though.

**Comment by barryvdh** [comment]
@mtdowling are you planning to remove the subtree splits for guzzle/http? Or is there another reason guzzle/http is deprecated in Packagist?

**Comment by mtdowling** [comment]
No, those subtree splits will be there forever. I just won't be updating them anymore. Guzzle 3 isn't going to get many more updates, so this may be a non-issue. If you want to switch to a non deprecated package, use guzzle/guzzle (still version 3 but just contains a bit more code).

**Comment by philsturgeon** [comment]
Looks like Omnipay should switch to guzzle/http on a minor, then [guzzlehttp/guzzle](https://packagist.org/packages/guzzlehttp/guzzle) v5.2 for a major.

**Comment by barryvdh** [comment]
You mean guzzle/guzzle. We're already on guzzle/http. But indeed, shouldn't have much impact.

Upgrading to guzzlehttp would be a pretty big impact, because all adapters rely on Guzzle.. And I guess there isn't an immediate need for an upgrade.

**Comment by kayladnls** [comment]
The next major of Omnipay is going up to Guzzle 5, for a number of different reasons. 

I can change our current dependency to guzzle/guzzle v3 without much impact, I believe. I'll play with it tonight.

**Comment by deviarte** [comment]
@kayladnls Which means that the min. PHP requirement will be upped to: "php": ">=5.4.0"

**Comment by kayladnls** [comment]
@deviarte yes, that's correct. Which would have happened regardless of the dependencies, as 5.3 is end of life.

**Comment by deviarte** [comment]
@kayladnls 5.3 is indeed end of life. But in our case we use Omnipay for a CMS plugin and they still at 5.3. Shame really, 5.4 adds some nice features like traits.

**Comment by philsturgeon** [comment]
We’re having this conversation all over the League at the moment. 

While dropping 5.3 for the sake of it is a sad move, and I know CMS’ are stuck on old decencies for the sake of their marketshare, at some point the League has to commit to updating its minimum version or they’re stuck in a loop of not being able to use new features.

CommonMark has decided to leave 0.7.0 available for the 5.3 users and move onto PHP 5.4 for the next versions.

https://github.com/thephpleague/commonmark/pull/76

I suggested people consider doing the same for other packages

https://groups.google.com/forum/#!topic/thephpleague/yVKgoY3YFq4

If Omnipay moves on a major and offers bug fixes downstream for a little bit then its not the worst position to be stuck in. Omnipay 2.3 is a good product, and Omnipay 3.0 can switch to 5.4 if it likes without forcing all of its users to upgrade.

**Comment by kayladnls** [comment]
A PR has been merged into omnipay-common to fix this.
