### ISSUE TITLE
saving params between requests

### ISSUE THREAD

**Issue by nicdnepr** [thephpleague/omnipay#236]
i googled many information about this, looked official examlpes but still has some doubts about this.

the main problem is with params between responses

first step, i must create $params and than i pass them to

    $request = $gateway->purchase($params)->send();

after redirect to paypal and pay, user redirect to success url. now i must call

    $response = $gateway->completePurchase($params)->send();

in official example $params store in session, but is this safe? user leave site, and go to paypal. user can spend some time in paypal and after return to site session can be destroy and site can't be process payment

i found some another solution. after call

    $request = $gateway->purchase($params)->send();

i can get data

    $data=$request->getData();

$data['TOKEN'] contains token, i save payment info in table with key token.

user redirect to paypal, pay and paypal redirect user to success url with querystring params token=&PayerID=

i guess token is permanent between purchase and completePurchase , is this correct to compare token from $data with token in querystring?

**Comment by kayladnls** [comment]
Yes, you can compare the tokens, as they should match. 

As far as how you store the parameters, that's completely up to you. Depending on the length of your session, it should be fine to put them there. If you don't feel comfortable with that, putting the params in a table will work just as well. That's left to your discretion.
