### ISSUE TITLE
iATS driver

### ISSUE THREAD

**Issue by mbrowne** [thephpleague/omnipay#237]
Hi,
I wrote a driver to support the iATS gateway (https://www.iatspayments.com/). I haven't had a chance to create a composer.json file and tests for it yet and to fork the project according to your guidelines, but in the meantime I thought I would let you know about it:

https://github.com/mbrowne/omnipay-iats

Thanks for this great library.

**Comment by kayladnls** [comment]
@mbrowne thanks for doing that! Once you've got composer set up, and test coverage, I'd be more than happy to list this gateway in the README as one of the supported gateways! Just let me know. 

Thanks, again.
