### ISSUE TITLE
Insuficient parameters for the PayPal Items + partial Solution

### ISSUE THREAD

**Issue by robuedi** [thephpleague/omnipay#240]
In the PayPal Gateway (omnipay/omnipay/src/omnipay/paypal/messages/ExpressAuthorizeRequest)  is only one parameter for the items.
Currently this parameter looks like this:
        $data['PAYMENTREQUEST_0_DESC'] = $this->getDescription();

In PayPal an items has many others parameters. Other parameters that should be added are:
        $data['L_PAYMENTREQUEST_0_NAME0']      =  $this->getName();
        $data['L_PAYMENTREQUEST_0_AMT0']         = $this->getAmount(); 
        $data['L_PAYMENTREQUEST_0_NUMBER0'] = $this->getNumber(); 
        $data['L_PAYMENTREQUEST_0_QTY0']         = $this->getQuantity(); $
        $data['ITEMAMT']                                               = $this->getDescription();

**Comment by kayladnls** [comment]
This issue was moved to thephpleague/omnipay-paypal#53

**Comment by kayladnls** [comment]
Moved this to the paypal gateway.

**Comment by TheSoftwareFarm** [comment]
Helper::validateLuhn(Input::get('card_number'))
