### ISSUE TITLE
PayPal client details not refilling (missing parameter) + Solution

### ISSUE THREAD

**Issue by robuedi** [thephpleague/omnipay#241]
When sending client details to PaPal (like adress, name) the automatic refill is not happening. This is caused by the missing of two parameters that should be added in the PayPal Gateway (omnipay/omnipay/src/omnipay/paypal/messages/ExpressAuthorizeRequest):
            $data['ADDROVERRIDE'] = 1;

The solution code would look like this:
            if ($card = $this->getCard()) {
                $data['ADDROVERRIDE'] = 1;
                $data['PAYMENTREQUEST_0_SHIPTONAME'] = $card->getName();
               $data['PAYMENTREQUEST_0_SHIPTOSTREET'] = $card->getAddress1();

**Comment by kayladnls** [comment]
This issue was moved to thephpleague/omnipay-paypal#54
