### ISSUE TITLE
Off site example

### ISSUE THREAD

**Issue by andreas22** [thephpleague/omnipay#246]
Hi,

I would like to make an implementation of a provider which is off site.

Based on documentation there are 2 purchase methods, which I copy/paste below for reference. If I am not mistaken, I will use purchase($options) to collect the required information from the user and then redirect to payment provider gateway. 
For handling the callback I will use completePurchase($options). 

Any feedback is welcome

purchase($options) - authorize and immediately capture an amount on the customer's card
completePurchase($options) - handle return from off-site gateways after purchase

**Comment by kayladnls** [comment]
That is correct. A good example of this is seen in the [Paypal Gateway](https://github.com/thephpleague/omnipay-paypal/blob/master/src/ExpressGateway.php#L131-L139). 

Let me know if you have any other questions.

**Comment by andreas22** [comment]
Hi,

I have created a new gateway that implements off side purchase using Fasapay, I would appreciate if you could take a look and give me your feedback.

https://github.com/andreas22/omnipay-fasapay

**Comment by kayladnls** [comment]
This: https://github.com/andreas22/omnipay-fasapay/blob/master/src/Helpers/Security.php#L13-L16 would be a good PR into the omnipay-common repo for Helper.php, I think. 

In PurchaseRequest you're overriding the get/setTestMode functions, with little to no change, other than casting to bool. 

Other than that, i think it looks great.
