### ISSUE TITLE
Omnipay skeleton

### ISSUE THREAD

**Issue by barryvdh** [thephpleague/omnipay#263]
Is there any need/interest in a Omnipay gateway skeleton package, similar to the phpleague one?

Just with an example Gateway, one method and a few examples methods, tests etc.

I've created that pretty much now I think, not sure if I should put it up thephpleague/omnipay-skeleton or something? If so, @kayladnls can you create the repo and grant me access?

**Comment by kayladnls** [comment]
@barryvdh I think it's an awesome idea. 

You should have access here: https://github.com/thephpleague/omnipay-skeleton

**Comment by barryvdh** [comment]
Ok thanks.

I've put up the basic stuff, mostly based on the paypal one (because that's the most popular)

If you (or anyone else) has any ideas/suggestions, let me know! Probably best by just creating an issue there :)
