### ISSUE TITLE
Braintree

### ISSUE THREAD

**Issue by bryglen** [thephpleague/omnipay#269]
No Braintree support for this?

**Comment by cfreear** [comment]
Not yet but there is a [skeleton Braintree repository](https://github.com/thephpleague/omnipay-braintree) and you are welcome to contribute.

**Comment by kayladnls** [comment]
@cfreear is correct. There isn't a fully developed gateway, but it has been requested several times, so I created a base repo to start work on it there. PRs are more than welcome.

**Comment by barryvdh** [comment]
Initial implementation is up in the Braintree repo. Feedback is welcome
