### ISSUE TITLE
Add 'recommends' to composer.json

### ISSUE THREAD

**Issue by kayladnls** [thephpleague/omnipay#273]
Move 3rd party gateways into 'recommends' in composer.json.

**Comment by barryvdh** [comment]
Suggest, not recommends ;)
https://getcomposer.org/doc/04-schema.md#suggest

**Comment by barryvdh** [comment]
I've added them to suggest, see above commit.

**Comment by barryvdh** [comment]
Good thing, https://packagist.org/packages/omnipay/omnipay links the packages and directly showed that we made 1 typo and 1 package doesn't exist on Packagist: https://github.com/aTastyCookie/yandexmoney_omnipay
Should we remove it?
