### ISSUE TITLE
[3.0] isSuccessful() - fix misnomer?

### ISSUE THREAD

**Issue by judgej** [thephpleague/omnipay#275]
This has always bothered me.

The `isSuccessful()` method may have made sense in early days for simple server-to-server transaction requests that either succeeded or failed, but makes less sense when there are other actions that need to be taken.

For example, if a redirect is needed, then `isSuccessful()` returns `false` to indicate "actually was a success, but there is another step to do".

It seems to me that its action meaning is "transaction is complete", so would it make sense to0 have a `isComplete()` or similar named method to indicate this? The `isSuccessful()` method would then relate entirely to whether the underlying transaction was successful or not - an authorisation request could be "unsuccessful", and get still "complete" and still not have a redirect involved.

**Comment by davelopware** [comment]
+1

**Comment by kayladnls** [comment]
I'm on board with this.

**Comment by Jellyfrog** [comment]
Me too, but it still won't be much of a difference for gateways that only gets callbacks.
Maybe its better to go for something more verbose like... `isRequestSuccessful()` terrible long but at-least it explains itself... some other variants are `isRequestOk()`, `isRequestComplete()`

Also, might be a better idea to go with `isPaid()` for "transaction is complete"

**Comment by barryvdh** [comment]
`isComplete()` makes sense for me. So would this keep both methods?

**Comment by Jellyfrog** [comment]
@barryvdh if you implement two gateways, say for example a credit card based and a "redirect" one, what is `isComplete()` then?
IMO it should be something where you can always verify with the same flow, no matter if it's a "redirect" or "direct" or some other notification based...
```
if request is ok
  if redirect
    // redirect user
  if payment ok
    // success
else
  // display error
```

**Comment by barryvdh** [comment]
Why not throw an Exception when something 'unexpected' happens?

**Comment by judgej** [comment]
The problem here is that all these suggested functions provide a boolean response. In reality there are a host of actions that will be necessary to perform, including a GET redirect, a POST redirect, providing an additional form for further details, 3DSecure redirect, as well as no further action because the transaction is complete or has failed.

A big bunch of boolean results just makes things much more complicated, as you need to check multiple methods before you can really decide what to do (e.g. Is it complete? No. So do we need to redirect? No. So did we get a warning? Yes. etc.

I think there are a limited number of next-step actions (half a dozen at a guess) that will cover all the gateways. We could give each a name, and that would tell the application what to do next. Think of it like a `switch` statement instead of the nested `if....then...else` that we have now.

Actions that are different again, can be declared with custom names in those gateways that need them.

Helper boolean methods such as "are we complete yet?", "are we still on track?" and "was the transaction successful" will still be useful alongside the next action indicator. This would apply equally to the initial transaction request as it does to the notify/callback handlers.

@barryvdh I use four different gateways, and that nested `if...then` flow definitely does not cover all the required flow.

**Comment by barryvdh** [comment]
But can we assume that usually, a request will succeed when it's valid? So otherwise, we can throw an exception.
In this case we can remove is isSuccessful and isFailed, right?

**Comment by aimeos** [comment]
I don't think so. If a request returns successfully, it doesn't necessarily mean that the payment was successful too. Especially, if there will be more status values than success/failed.

**Comment by barryvdh** [comment]
I didn't mean that. I meant, if the request itself isn't successful, it can throw an exception.
A redirect or pending doesn't throw an exception. So isPending(), isRedirect() and isCompleted() still work, but isSuccessful is implied.

**Comment by aimeos** [comment]
From that perspective it sounds OK

**Comment by barryvdh** [comment]
Closing in favor of https://github.com/thephpleague/omnipay/pull/347
