### ISSUE TITLE
is there any example width laravel5

### ISSUE THREAD

**Issue by beysong** [thephpleague/omnipay#276]
is there any example width laravel5? thanks in advance!

**Comment by cfreear** [comment]
While you should be able to use Omnipay with Laravel 'out of the box' there are a number of packages available to integrate Omnipay into the Laravel ecosystem, I would recommend @barryvdh's [laravel-omnipay](https://github.com/barryvdh/laravel-omnipay). Barry has done some excellent work with Laravel and has made a number of contributions to the Omnipay family of repos so it's a natural choice.

**Comment by cfreear** [comment]
Another option by @ignited: [laravel-omnipay](https://github.com/ignited/laravel-omnipay)

This package is more popular than @barryvdh's but that could just be because it's older. It does require PHP 5.4 (barryvdh/laravel-omnipay requires 5.3) and there isn't a license (barryvdh/laravel-omnipay is MIT). YMMV.

**Comment by barryvdh** [comment]
Yeah but honestly, if you just use 1 gateway, no need for a laravel package.

**Comment by judgej** [comment]
If you use multiple gateways, having a package to handle all the configuration for them in one place, makes selecting gateways at run time much easier using one of these packages.

I've used the ignited package on L4 with three gateways (several of those operating over multiple currencies) and it worked a dream. I'm not sure that package was ever updated for L5 though.

**Comment by cfreear** [comment]
Ah I knew I'd missed something. Both support Laravel 5.0, ignited/laravel-omnipay has a 2.0 branch for L5 while maintaining L4.2 support on their 1.1 branch.

**Comment by beysong** [comment]
thank you all and ignited/laravel-omnipay is just what I need.

**Comment by devZstudio** [comment]
i am receiving this error.
The requested package barryvdh/laravel-omnipay could not be found in any version, there may be a typo in the package name.

**Comment by judgej** [comment]
@devZstudio do you want to show us what you are doing to get this error? Better still, raise it as a new issue here: https://github.com/barryvdh/laravel-omnipay (sorry Barry ;-)
