### ISSUE TITLE
[3.0] Proposal: More status values than "yes/no"

### ISSUE THREAD

**Issue by aimeos** [thephpleague/omnipay#281]
Using the current Omnipay API we can only check if a payment was successful or failed. This is enough in most cases for credit card payments but even there can a status like "pending" occur. Furthermore, it's not possible to update the order status if notifications sent by payment gateways arrive that a payment was refunded.

Therefore, it would make sense that the Omnipay API can return a standard set of status values. We would suggest:
- 1 = canceled (payment was canceled by the customer)
- 2 = refused (payment was refused by the credit card company / bank)
- 3 = refunded (money was payed back to the customer)
- 4 = pending (payment is in progress, e.g. for off-line direct debit payments)
- 5 = authorized (payment was authorized)
- 6 = received (payment was captured)

Status values less than 4 mean "no money", 4 is "request was OK but real payment status will be known later) and values greater 4 are successful payments. Distinguishing between "authorized" and "received" allows shop owners to switch between authorization and capturing without the fear that they miss to capture outstanding payments and makes it more understandable for developers.

**Comment by judgej** [comment]
I saw this a couple of days ago, and although I think it is too specific to jump straight into as a proposal, it does highlight the fact that there are many statuses involved across the various gateways and services.

A complete list of normalised/standardised statuses would be very handy, and certainly feasible to put together. How the raw statuses of each gateway, in various contexts, then map onto the standard list of statuses can then be added.

It would be a simple status/status map. For example, a returned status of "OK" from SagePay can mean several different things, depending on which message it has been returned to (i.e. context), but that can be taken into account.

So yes, this is a good start, but I think needs widening out a bit to see how the gateways overall fit into a standard list. These statuses would ultimately all be nodes on a status state diagram for each gateway.

**Comment by lord2800** [comment]
I think if there's going to be a normalized map, there also needs to be a way to get the raw status from the gateway--that way for those statuses that don't map cleanly (i.e. they have additional semantics that need to be taken into account) there's a way to look into them and handle it.

**Comment by NoelDavies** [comment]
Agreed, but we need to widen these and add things like partial refund, etc.

**Comment by barryvdh** [comment]
I think it would be probably good to create a `getStatus()` code with more specificity. The `isCancelled()`, `isRedirect()`, `isSuccessful()` methods could be derived from this status.

**Comment by judgej** [comment]
@barryvdh Agreed. Derive the boolean results from the status, and not have all the gateways juggling combinations of boolean statuses around.

**Comment by kwilliams** [comment]
I think that payment state is too diverse in the gateway pattern. What about allowing each gateway to register a state machine, and implement methods to transition an internal state. This would allow each gateway to handle the transition of states in a controlled, and much more descriptive manner.

Something like this awesome project (no affiliation): 
https://github.com/yohang/Finite

**Comment by delatbabel** [comment]
We have a standardised list of statuses (error, pending, pending_payment, success, declined, approved, accepted, cancelled, refunded, processing) which we map to status codes. We then have an internal map to map the various gateway status codes to our status codes. We currently store that map in code but we probably should put in into a database.

We do the same thing for error codes (various numbers representing technical issues, declined, duplicate payment, invalid inputs, expired card, insufficient funds, etc), which we do store in a database table and then have another join table between gateway error codes and our error codes to allow us to quickly map the error codes to ones that we understand.

Then there's MultiCards which has one and only one error code "2" == "error". :)

**Comment by aimeos** [comment]
The state transition can be implemented in different ways but we should keep it simple. The best option is still to implement it in code without external storage - or to set the last payment status to the gateway before calculating the new status.

I would avoid at all cost storing this data in a database by Omnipay itself! This will create a heap of problems, from different database implementations to schema issues and abstraction layers.

**Comment by barryvdh** [comment]
FYI, this is the Payum list: https://github.com/Payum/Payum/blob/master/src/Payum/Core/Request/GetHumanStatus.php

- captured
- authorized
- refunded
- unknown
- failed
- suspended
- expired
- pending
- cancelled
- new

So if failed == refused and captured == received, these are extra in Payum:
new, unknown, suspended, expired

The unkown status could probably be the default, for when no more info is found. What do you think about the others?

**Comment by barryvdh** [comment]
Closing in favor of https://github.com/thephpleague/omnipay/pull/347
