### ISSUE TITLE
Feature Request - Mock/Test Gateway

### ISSUE THREAD

**Issue by AndrewCarterUK** [thephpleague/omnipay#284]
Hello,

I've searched to see if this exists but couldn't find it (I may just be poor at searching).

Would a TestGateway be inside the scope of this project?

At the moment I've got a TestGateway which I inject when I'm using classes that depend on a gateway. It seemed like a pretty common need - so I was wondering if it was considered inside the scope of the project?

If so - I could submit a pull request or leave it here as a suggestion.

Happy to hear thoughts!

Andrew

**Comment by kayladnls** [comment]
I'm not 100% sure how you mean. If you want to make the PR, so I can see the code, I think I'd be better able to discuss it.

**Comment by aimeos** [comment]
There's a dummy gateway available: https://github.com/thephpleague/omnipay-dummy

**Comment by AndrewCarterUK** [comment]
That's exactly what I mean, turns out I'm poor at searching ^

Thanks very much! Might be worth mentioning that in the documentation as it's very useful!
