### ISSUE TITLE
Readme examples PHP 5.4

### ISSUE THREAD

**Issue by iddqdidkfa** [thephpleague/omnipay#290]
In the begining of Readmy it says:
>An easy to use, consistent payment processing library for PHP 5.3+

In code sample you create array with:
```
$formData = ['number' => '4242424242424242', 'expiryMonth' => '6', 'expiryYear' => '2016', 'cvv' => '123'];
```
That is allowed only in PHP 5.4+

I know library supports 5.3, but it can be confuse for users with PHP 5.3 who will try to use example code.

**Comment by barryvdh** [comment]
Can you submit a PR to fix the example?

**Comment by iddqdidkfa** [comment]
@barryvdh If 5.3 not supporting anymore than example is good and you only have to update Readme.md  
>An easy to use, consistent payment processing library for PHP **5.4+**

**Comment by barryvdh** [comment]
No 5.3 is still supported.
If you want, you can submit a PR to make the readme 5.3 compatible.
