### ISSUE TITLE
New gateway implementation - Pagar.Me

### ISSUE THREAD

**Issue by gpassarelli** [thephpleague/omnipay#292]
Hi there,
I'm here to let you know that we have implemented a new gateway using Omnipay.

We have implemented Omnipay to be used with [Pagar.Me](http://pagar.me), a gateway here in Brazil.
You can checkout our code here:
https://github.com/descubraomundo/omnipay-pagarme

Let me know if you have feedback.

**Comment by kayladnls** [comment]
@gpassarelli This looks great. You can open up a PR to add the gateway to the README and the composer.json file and I'll happily merge it!
