### ISSUE TITLE
Confusing/missing info regarding CardReference vs Token 

### ISSUE THREAD

**Issue by yellow1912** [thephpleague/omnipay#293]
In the document, it seems to imply that the Token is the CardReference which can be used for Token Billing. However, in the code it seems like there are separate methods for getting and setting cardReference and Token which implies that they are different.

Is there any document where I can read for more information regarding the topic?

Best

**Comment by NoelDavies** [comment]
hey mate, Token is normally for the API token (JS generated) and CardReference is normally for an existing reference to a card. So, for example, if you save a card using stripe, you get a card reference back (stripe calls it a customer reference), but when doing normally transactions, you can use the Token provided by the gateway to use at the "token".

Hope this helps?

**Comment by delatbabel** [comment]
In all cases the gateway driver should be using the cardReference not the token. I have been fixing those few cases I've seen where setting a card reference requires setting the token parameter, in most cases it's a bug.

@NoelDavies is correct, token is normally the API authentication token such as the one used in PayPal connections.
