### ISSUE TITLE
Querying merchant for card details on a CardReference or TransactionReference?

### ISSUE THREAD

**Issue by dkisselev** [thephpleague/omnipay#298]
Once you call createCard, you get a CardReference back which is what we persist.

I'd like to be able to retrieve the details that the gateway has for a given cardReference (or transactionReference) but haven't seen any implementation or discussion about this.

The way I'm thinking about it is adding a $gateway->getCard() request to my gateway that's similar to createCard and returns the appropriate details (I'm working on a new gateway for a provider that we're using internally)

I'm looking for some feedback about whether that fits with the "Omnipay way" or if there might already be a method that I missed that gives a similar result.

**Comment by kayladnls** [comment]
Which gateway are you using?

**Comment by dkisselev** [comment]
I wrote my own gateway for our provider, but spent some time browsing the repositories for the other official gateways and didn't see any examples of this feature that I could replicate. I ended up creating a getCardProfile method that just returns an incomplete response object (no transaction details, just the card), but that's not overly clean or compatible with other gateways.

**Comment by delatbabel** [comment]
Not many gateways support this.  Fat Zebra has something similar where you can do a createCustomer() then a createCard() on that customer and later do fetchCustomer() to fetch the list of card tokens for that customer but in the generic case most gateways don't want to divulge any information about the card details so they won't generally implement a fetchCard() method.

**Comment by dkisselev** [comment]
I don't necessarily agree that few gateways have this feature, most of the time they'll supply things like the last four, expiry, and address. I randomly looked at the docs for Stripe and Braintree since they seem popular and they do implement it:

Stripe: https://stripe.com/docs/api#retrieve_card  
Braintree: https://developers.braintreepayments.com/reference/request/payment-method/find/php

If others are looking to implement this type of functionality, it might be useful for there to be a standard interface to follow, but this thread hasn't gained much traction so it's probably not a pain-point for people right now.

**Comment by delatbabel** [comment]
Having worked with several dozen payment gateways in my time I don't agree that finding two gateways that implement this feature is sufficient evidence to disprove the assertion that "not many gateways support this".

Yes, Braintree does, Stripe does, the majority of others don't.
