### ISSUE TITLE
I built a WePay Gateway but no test yet

### ISSUE THREAD

**Issue by Collizo4sky** [thephpleague/omnipay#303]
Hi, i built a WePay gateway and its working.

https://github.com/Collizo4sky/omnipay-wepay

But no unit test and CI set up just yet.

Am still new to unit testing, Ci and all that jazz. Any help will come in handy though am working hard to get this done.

cc @kayladnls

**Comment by dercoder** [comment]
If you still need help, please send me an email with your skype contact so we can chat.

**Comment by Collizo4sky** [comment]
Sure @dercoder done.

**Comment by dercoder** [comment]
I am online now @Collizo4sky

**Comment by Collizo4sky** [comment]
‎Joining you asap.                                                                                                                                                                                                                                         From: Alexander FedraSent: Monday, 28 September 2015 12:26 PMTo: thephpleague/omnipayReply To: thephpleague/omnipayCc: Agbonghama CollinsSubject: Re: [omnipay] I built a WePay Gateway but no test yet (#303)I am online now @Collizo4sky 

—Reply to this email directly or view it on GitHub.

**Comment by kayladnls** [comment]
@Collizo4sky Looks like you have some help. @dercoder thanks for stepping up! If either of you need anything from me, don't hesitate to ping. You can reach me on twitter at @kayladnls

**Comment by dercoder** [comment]
I have only one question. If the payment provider need some personal informations like first name, last name and email address. Should we use getCard()->getEmail() or should we create our own setters and getters for the purchase request?

**Comment by Collizo4sky** [comment]
@dercoder let me do the tagging of @kayladnls for you.

Very much interested in this 'cos that's the approach i took in my wepay gateway.

Once again, tihanks for your help via skype :+1:

**Comment by dercoder** [comment]
I think we can close this Issue

**Comment by Collizo4sky** [comment]
Thanks @dercoder for your help.. closing this right away..
