### ISSUE TITLE
How to get the order details from PayPal Express checkout?

### ISSUE THREAD

**Issue by bencromwell** [thephpleague/omnipay#305]
Hello,

Been searching for a while for an answer to this. How do you retrieve order details from PayPal such as the email address and shipping details of the user?

**Comment by cfreear** [comment]
try [fetchCheckout](https://github.com/thephpleague/omnipay-paypal/blob/master/src/ExpressGateway.php#L146) passing the transaction ref you got from your authorize/purchase call as a ``token`` parameter.

**Comment by bencromwell** [comment]
Perfect, thanks

**Comment by Artem-Schander** [comment]
Hi, either I'm blind or I'm missing something. The result I'm getting out of `getData`has no customer related information.
I have only the following:
```
'VERSION'
'USER'
'PWD'
'SIGNATURE'
'SUBJECT'
'METHOD'
'TOKEN'
```
