### ISSUE TITLE
In AbstractResponse, what is the intent isTransparentRedirect() ?

### ISSUE THREAD

**Issue by Collizo4sky** [thephpleague/omnipay#306]
See https://github.com/thephpleague/omnipay-common/blob/master/src/Omnipay/Common/Message/AbstractResponse.php#L95

cc @kayladnls  @dercoder

**Comment by judgej** [comment]
It's a term that unfortunately points to a number of different implementations, so be wary about a single description of its intent *now*. A transparent redirect generally means that credit card details do not pass though your site, even though your site hosts the full payment form.

I've seen this implemented in at least two different ways, with many variations on the details:

* A JS function triggers on form submission, submits the credit card details direct from your browser to the payment gateway using AJAX, gets a token in response, puts the token into your form then submits the form to your site. Your site submits the rest of the details and the card token via a back channel.
* The payment form in its entirety is submitted direct to the payment gateway from your site, with the result being sent to a back-channel, which then instructs the gateway to redirect back to the front end of your site.

Te above may involve a back-channel to get temporary access tokens for the front-end JS to use in its AJAX call. Some don't (and I think that is insecure).

This `isTransparentRedirect()` flag signifies that something like the above happens with the URL supplied - it is either the URL the AJAX POSTer uses, or the URL the whole form is POSTed to.

**Comment by judgej** [comment]
On top of this, there are 3DSecure URLs that I am not sure has ever really been handled by OmniPay. So there may be a transparent URL used by your browser for the AJAX, then another URL used by your back-end to submit the rest of the form. That submission may then result in another URL that the user needs to go to (or is brought up in an iframe) for a 3DSecure PIN check.

**Comment by Collizo4sky** [comment]
Thank you.
