### ISSUE TITLE
Is there a way of getting all available gateways not just supported ones?

### ISSUE THREAD

**Issue by laverboy** [thephpleague/omnipay#307]
As the question says, I am aware of `Omnipay::find()` but this only gets officially supported gateways. I would like to also include the third party ones and ones I include myself.

This is in order to show the end user the available gateways and then show them the required default parameters when they select one. Thanks.

**Comment by kayladnls** [comment]
I could add this feature but it would require cloning down all of the gateways, native and third party. That would entail a lot of repositories. 

Could you help me understand the use case a little better so I know what you're looking for?

**Comment by laverboy** [comment]
Sorry not responded sooner.

Essentially I am trying to do what the example [application does](https://github.com/thephpleague/omnipay-example/blob/master/index.php#L27-L35). It presents to the user all the available gateways. I then use the selected gateway to get the default parameters and insert the required fields in the form.

Hope that helps.

**Comment by laverboy** [comment]
I'm not wanting to push, but wondered if there was any movement on this? Thanks

**Comment by judgej** [comment]
What do you mean by "available"? Do you just want a list of the gateways that are currently installed, using whatever means you have? Or do you want a list of all gateways available anywhere, so that they can be pulled in and installed one demand?

**Comment by laverboy** [comment]
I'm after all the currently installed gateways. Basically everything that
is available to the admin user.

**Comment by judgej** [comment]
The only way I can see of doing that, is to run through the list of gateways that exist, and try to load up each in turn to see if they are installed. So I think it is back to that master list again. I don't think there is any way to detect that a third party gateway has been installed without knowing it exists in the first place.

Unless I'm missing it, I can see no way to get a list of the gateways for each driver either. So SagePay may have a `Direct` gateway and a `Server` gateway, but there is no metadata to allow you to discover that, even if you know the SagePay driver is installed.

Sorry if I'm just restating the problem - but hopefully I can be corrected, or if not, we can understand better where the solution needs to go.

So far, I think we need better metadata within the drivers, so we can see what gateways they support. And secondly a central list of drivers and gateways from all sources. Maybe composer tags would help us here.

**Comment by kayladnls** [comment]
I see no way to detect which gateways are installed. You could probably parse your own composer.json and look for `omnipay` in the package name, as most of the packages are `third_party_vendor_name/omnipay_*` or similar. 

As for checking which gateways each driver supports, there is a Gateway file for each gateway as [here](https://github.com/thephpleague/omnipay-sagepay/tree/master/src), that could be iterated over and parsed.

That said, both of those solutions are rather messy.

**Comment by judgej** [comment]
Something I looked at a while ago, was to see if composer could be interrogated for a list of packages that are installed. That turns out even messier, as the internals of composer are a bit of a mystery (to me, at least). In theory the composer package can be installed, loaded up and the API it offers uses to do the interrogation. Last time I looked, all the API methods that looked useful seemed to be private or protected.

**Comment by barryvdh** [comment]
You can specify a package type; https://getcomposer.org/doc/04-schema.md#type
You can also create a plugin that hooks into install/update commands and list the packages, check the package type etc. 
Or list the gateways in the meta part of composer.json, and check that in your plugin.

But I think for most cases it doesn't make sense. What if you have REST and SOAP driver? You don't want to show both. And you have to configure them anyways.

I think it would make more sense to create a GatewayManager or sorts, where you can register available gateways (including configuration, like API keys, default params etc), and list those somewhere.

**Comment by kayladnls** [comment]
I agree with Barry here. It's not something I would recommend doing automatically. I think it would require a little more oversight than parsing through `composer.json`

It's not something that we would support with this package, though. I'm going to close this issue.

**Comment by laverboy** [comment]
No worries - thanks all for your time. In the end we went for adding 'extra' information to our composer.json file and parsing it, to show which gateways we had installed.
