### ISSUE TITLE
For ideal is there a package ??

### ISSUE THREAD

**Issue by costinbogdan** [thephpleague/omnipay#331]
Hi everyone. For ideal payment method is there a package ?? please give me all the details if you have a package . I need to use for laravel. Thanks guys

**Comment by barryvdh** [comment]
There are multiple drivers with iDeal support. Depends on the gateway you use:

https://github.com/fruitcakestudio/omnipay-sisow
https://github.com/payproNL/omnipay-paypro
https://github.com/thephpleague/omnipay-rabobank
https://github.com/thephpleague/omnipay-mollie
https://github.com/thephpleague/omnipay-multisafepay
https://github.com/thephpleague/omnipay-buckaroo

etc

**Comment by costinbogdan** [comment]
Hi
I installed https://github.com/fruitcakestudio/omnipay-sisow for iDeal support  but it give to me 
Error TA3220: Merchant not found. 
I think i need this data 
             'shopId' => '',
            'merchantId' => '0123456',
            'merchantKey' => 'b36d8259346eaddb3c03236b37ad3a1d7a67cec6',


How to get this data? Can you help me? I am new with this. 

Thanks guys.

**Comment by barryvdh** [comment]
You need to signup with a payment gateway provider first, to acquire those keys.

**Comment by costinbogdan** [comment]
"You need to signup with a payment gateway provider first, to acquire those keys" 
How to do that? Please can you tell me??

**Comment by costinbogdan** [comment]
"You need to signup with a payment gateway provider first, to acquire those keys" 
How to do that? Please can you tell me?? 

    În Miercuri, 3 Februarie 2016 12:24:32, Barry vd. Heuvel <notifications@github.com> a scris:
 

 You need to signup with a payment gateway provider first, to acquire those keys.—
