### ISSUE TITLE
[3.0] Sensitive Value Object

### ISSUE THREAD

**Issue by barryvdh** [thephpleague/omnipay#335]
When looking into Payum, I came across a [SensitiveValue object](https://github.com/Payum/Payum/blob/master/src/Payum/Core/Security/SensitiveValue.php)
(docs: https://github.com/Payum/Core/blob/master/Resources/docs/working-with-sensitive-information.md)

While it may be the responsibility of the developer to handle data, we could make it less error prone. The information in the CreditCard object should be handled as sensitive information (especially creditcard number+expiry, but also name/address).

If something goes wrong, eg. an error occurs, error handlers could dump the stacktrace/context, which could end up in logs etc. Should we make sure that the CreditCard object is more secure by default?

**Comment by judgej** [comment]
Sounds like a very good idea. PCI compliance is not something to be taken lightly.

**Comment by kayladnls** [comment]
I like this idea. :+1:

**Comment by barryvdh** [comment]
For now I've masked the json_encode, print_r and var_dump() output, to show just the last 4 numbers of the CC (so it can be used to verify something atleast), and hide the expiry month/year, cvv and issue number; https://github.com/thephpleague/omnipay/commit/65bc7ce161bfd747aceb5d1a95acff7e07a9cc5d
(__debugInfo only works on 5.6+)

What do you think? This isn't as explicit/strict as the linked example, but should account for accidental dumping of CC data in logs..

**Comment by barryvdh** [comment]
Marking this as fixed for now, as no one has better ideas ;)
