### ISSUE TITLE
Add a new gateway - Komerci (Rede)

### ISSUE THREAD

**Issue by byjg** [thephpleague/omnipay#340]
I developed a new gateway driver for Komerci (Rede).  

Komerci is the solution for e-commerce from Rede (former Redecard). Rede is a Brazilian acquirer. This is responsible for the authentication, authorization and capture the card data in the Rede environment. 

How I get this driver listed here: https://github.com/thephpleague/omnipay ?

The repository of this gateway is:
https://github.com/byjg/omnipay-komerci/

Thank you.

**Comment by delatbabel** [comment]
You get the driver listed by submitting a PR for this package.  Update the README.md file with the name and link to your new gateway driver.

**Comment by byjg** [comment]
Thank you, I created the PR right now.
