### ISSUE TITLE
PCI Compliance

### ISSUE THREAD

**Issue by volomike** [thephpleague/omnipay#356]
Stripe has this to say about PCI compliance with their product:

https://support.stripe.com/questions/do-i-need-to-be-pci-compliant-what-do-i-have-to-do

So, if I use OmniPay, does it utilize stripe.js? If not, then I may have to do quite a bit of PCI compliance changes and quarterly PCI auditing to use OmniPay, wouldn't I?

**Comment by barryvdh** [comment]
It does, see https://github.com/thephpleague/omnipay-stripe#stripejs
