### ISSUE TITLE
ΠΡΟΒΛΗΜΑ ΜΕ ΤΗ ΔΙΑΣΥΝΔΕΣΗ ΤΟΥ ESHOP ME VIVAPAYMENTS.COM

### ISSUE THREAD

**Issue by divramis1** [thephpleague/omnipay#360]
Αξιότιμοι κύριοι τεχνικοί, λύστε με το πρόβλημα διασύνδεσης του eshop που δεν μπορώ να σας αποκαλύψω ποιο είναι για ευνόητους λόγους.
Τι φταίει ενόσω τα έχω κάνει όλα σωστά;

Μην φταίει το hosting; και πως θα το καταλάβω;
Μην φταίνε τα plugins; και πως θα το μάθουμε;
Μην φταίει κάτι άλλο; και πως θα το μάθετε;
Ελέγξτε το eshop μου και άμα βρείτε άκρη , τρυπήστε με τη μύτη.

Γιάννης ΔΙβράμης
6972364387

Η χειρότερη τεχνική υποστήριξη στον κόσμο είναι η δική σας για τη VIVAPAYMENTS.
Δεν υπάρχει καμία τεχνική υποστήριξη, αφήστε τον παπά από τα αρχίδια παιδιά και κάντε καμιά δλεια

**Comment by delatbabel** [comment]
We do not provide support for VivaPayments.  Contact the company directly.
