### ISSUE TITLE
Contribution of gateway for sofort.com

### ISSUE THREAD

**Issue by aimeos** [thephpleague/omnipay#366]
We would like to contribute a driver for sofort.com including full code coverage as Omnipay project. The driver is based on the https://github.com/ismailasci/omnipay-sofort/ implementation and has been improved and bugs fixed: https://github.com/aimeoscom/omnipay-sofort/tree/omnipay

Can you please create a new repository and tell us how to proceed?

**Comment by barryvdh** [comment]
I would rather wait and see if @ismailasci is interested in maintaining his library. If hoe doesn't want to, or doesn't respond for a long time (as the project didn't receive regular update for a while), we can point to your new repository.

You don't need to create a new repository for that, you can use your personal organisation.

**Comment by aimeos** [comment]
There have been no update and response to issues or pull request since Nov. 2014 so it's unmaintained for 2,5 years now. He also made no contributions for at least one year to no GitHub repository at all and the last update on his web site was 2011. So I assume that there will be no more maintenance in the future.

I know that we can leave it in our own repository but we would like to make this an official Omnipay driver to ensure maintenance in the future. Therefore, we worked hard to meet all requirements for this.

**Comment by delatbabel** [comment]
Best thing to do is to create the driver in a public github repository. We can then link to it from here. If you want thephpleague to take over maintenance of it at some point in the future then we can do that but it requires a certain level of code maturity and documentation. So best create the driver first and then let us take a look at it rather than have us speculating on maintenance of something that hasn't been written yet.

**Comment by aimeos** [comment]
@delatbabel The Omnipay driver for sofort.com is already available and code coverage is 100%:
https://github.com/aimeoscom/omnipay-sofort/tree/omnipay

If anything is missing for a take over, please drop us a note.

**Comment by delatbabel** [comment]
OK so the next thing to do is to submit a PR for this repository changing the README to point to your new gateway code and indicating that the previous one is deprecated.  See where 2checkout is listed as an example.

**Comment by aimeos** [comment]
@delatbabel 
The ismailaci/omnipay-sofort repository has never been added to the Omnipay list of drivers:
https://github.com/thephpleague/omnipay#payment-gateways

At the moment, our aimeos/omnipay-sofort repository is just a fork with bugfixes, improvements and full code coverage but without composer package on packagist because we would like to make it available as omnipay/sofort as soon as it's accepted.

**Comment by delatbabel** [comment]
Generally thephpleague only take over maintenance of a driver once it has an established user base, test suite, verification that it works in production, etc.  Probably best to just add the aimeos/omnipay-sofort driver as it stands to the README and we can look at taking it on as an official driver later.

http://omnipay.thephpleague.com/gateways/build-your-own/

**Comment by aimeos** [comment]
The original omnipay-sofort package is available since 3 years, the composer package has 53k downloads, the test suite covers the code to 100% now and we use it in production.

We are not interested in publishing a fork of the original package but only in helping to make this package ready for official takeover.

@delatbabel Would be nice if you could reopen this issue until this has been sorted out :-)

**Comment by delatbabel** [comment]
ok

**Comment by cfreear** [comment]
I'm not a member of @thephpleague but as far as I'm aware of the process test coverage and longevity doesn't automatically make a package eligible for adoption. It would need to be voted in and someone would need to volunteer to maintain it. @thephpleague is made up of volunteers and isn't a commercial organisation.

**Comment by barryvdh** [comment]
I think we might need to discuss this, but I'd rather not include all community gateways in the league repos, but just link to the gateways.

Using the omnipay (or league) namespace/repos suggest something 'official', while in practice, most are not maintained by the php league.

**Comment by aimeos** [comment]
@cfreear Well, it shouldn't be a new top level project of phpleague but only a driver for the existing Omnipay project. So the phpleague won't care about this.

@barryvdh What was the criteria to become an 'official' driver in the past?

**Comment by barryvdh** [comment]
Not sure, but in the past, all gateways were included when requiring the package, so it was a bit different. We don't do that anymore (or atleast don't add new ones). It makes zero difference in which namespace it is.
Imho it would be more benefitial for you (or your company) to use your company repository organisation (in terms of publicity)

**Comment by cfreear** [comment]
Prior to adoption by @thephpleague Omnipay was a private project and all the @omnipay repositories were created by that individual. Even though they are under the @omnipay organisation they are by extension @thephpleague packages.

A lot of the gateways are maintained by people who use them and, in my opinion, this is the best way to do it as a general maintainer might not keep up to date with API changes like a consumer of that service would.

I presume you will be using this package, is there any particular reason you don't want it under your organisation?

**Comment by delatbabel** [comment]
If everyone's OK with it then I can take over maintenance, however my knowledge of German is limited (that is, limited to google translate) so perhaps it would be best for someone who does speak German to obtain some test accounts for me.

**Comment by aimeos** [comment]
@delatbabel It doesn't make much sense if you take over maintenance personally. Our hope was that the driver would be "official" when the requirements are met but as @barryvdh said, no more drivers will get this status.

Therefore, we will maintain the omnipay-sofort driver in the future because our customers are using it. Also, it seems like we will create to improve more drivers in the future.

**Comment by barryvdh** [comment]
Good to hear that :)
I was hoping to off-load the maintenance to developers who are actually using them, to prevent 'abandonded' gateways.
