### ISSUE TITLE
PHP Version

### ISSUE THREAD

**Issue by dercoder** [thephpleague/omnipay#367]
Should we still support 5.3 and PHP 5.4?
https://en.wikipedia.org/wiki/PHP#Release_history

**Comment by judgej** [comment]
For OmniPay 2.x I think yes. Legacy sites can run on for years with other things preventing upgrades. For OmniPay 3.x there is a big fresh horizon stretching out ahead of us, so the rules can be changed.

I suspect there is already another issue covering this question.

My 2p.

**Comment by cfreear** [comment]
PHP version support can't be changed for 2.x really as it would be a breaking change. v3.x is currently on track to support >= PHP 5.5 #274

**Comment by dercoder** [comment]
Thx :)

**Comment by barryvdh** [comment]
Yes I just bumped v3 to 5.6, as 5.5 stops having security updates in 10 days http://php.net/supported-versions.php
 :)
