### ISSUE TITLE
Add EgopayRu gateway

### ISSUE THREAD

**Issue by pinguinjkeke** [thephpleague/omnipay#393]
Gateway: https://tws.egopay.ru/docs/v2/
Package: https://github.com/pinguinjkeke/omnipay-egopaymentru
Maintainer: Alexander Avakov https://github.com/pinguinjkeke

Should I create PR on common repo? I read here that there is no need for it
https://github.com/thephpleague/omnipay-common/pull/8

**Comment by delatbabel** [comment]
No there is no need for a PR on the common gateway.  Instead what you should do is to make a PR on this (thephpleague/omnipay) gateway adjusting the README.md file to include links to your new gateway.  See the format of the current entries in the README.md file for examples.

Thanks for the contribution.
