### ISSUE TITLE
Noop Payment Gateway

### ISSUE THREAD

**Issue by alexbowers** [thephpleague/omnipay#399]
There are cases when a payment requires no action on the systems part, other than to consider it processing; but the API being kept consistent is useful.

In this case, a noop gateway will allow for this.

Use Cases:

- Pay in store / on collection
- Bank Transfers
- Instore Credit

**Comment by delatbabel** [comment]
That is exactly what the manual gateway does.

**Comment by alexbowers** [comment]
Thanks, Didn't see that.
