### ISSUE TITLE
Get amount from response in gateway-independent way

### ISSUE THREAD

**Issue by regularjack** [thephpleague/omnipay#403]
Is it possible to retrieve the *processed* amount from the response in a gateway-independent way?

For example, when using the Stripe gateway, I would `authorize` a payment as follows (`authorize` is an example, this question applies to all gateway methods):

```php
    $options = [
        'amount' => '10.00',
        'currency' => 'EUR',
    ];
    
    $response = $gateway->authorize($options)->send();
    
    if ($response->isSuccessful()) {
        $data = $response->getData();
    
        $amount = $data['amount'] / 100;
    }
```

Since Stripe works in cents, I'm forced to divide by `100` to get the amount in the same unit as I specified it, in the request. 

However, not all gateways work in cents, which means the code above is not gateway-independent. Also, the `amount` parameter might not even be called the same in other gateways.

**Comment by barryvdh** [comment]
This is a good idea. In v3 we're going to use a Value object for passing the Amount to the gateway. We should also use that in case the gateway returns it back.

**Comment by regularjack** [comment]
Should this be added to the v3 milestone?

**Comment by barryvdh** [comment]
Okay with this?
https://github.com/thephpleague/omnipay-common/commit/5e8236689f27f396a72066558ef383e8693ac03e

Adds it to the interface. Not really enforcing, but gateways should implement null or AmountInterface.

**Comment by regularjack** [comment]
That's great, thanks!
