### ISSUE TITLE
WorldLine (SIPS) Gateway

### ISSUE THREAD

**Issue by BrainFeeder** [thephpleague/omnipay#408]
Any chance of adding a gateway for WorldLine?

http://worldline.com/en-us/home/solutions/financial-processing-software-licensing/online-banking.html

**Comment by delatbabel** [comment]
Are you suggesting that you'll create one and we can add it to the list of gateways for this package? Yes sure.

Are you asking if someone else will create one for you?  No, probably not.  There are a few devs for hire that will do it on a cost-for-time basis, however a quick look at the WorldLine web site reveals no API documentation, and it appears that you have to pay for a software license to use their gateway code, so it's actually very unlikely to happen in an open source project like Omnipay.

**Comment by BrainFeeder** [comment]
I thought maybe someone allready started creating it. I could do it myself, if I had time. The documentation is send once a client subscribes to the service. 

That being said, I only use the service because my boss picked them.. I don't like the service and the support isn't very customer friendly.. So I'll guess I use 'Omnipay does not support it' as an excuse to let my boss pick another service for future projects ^^

**Comment by delatbabel** [comment]
> The documentation is send once a client subscribes to the service. 

Assuming that the reason for this is that there are non-disclosure clauses in the documentation, this means that Omnipay can absolutely never support this gateway and is a suitable reason by itself to pick another service.
