### ISSUE TITLE
Feature request - SumUp payment (online and by cardreader)

### ISSUE THREAD

**Issue by AccessWebBE** [thephpleague/omnipay#412]
I'm hoping to be on the right place for this, I'm actually not a coder but I think it would be nice to have Omnipay support SumUp payments?

**Comment by delatbabel** [comment]
Yes it can be done but someone needs to build the gateway code and submit a PR to link to it.  If you're not a coder and you need it done for some reason then find someone who is a coder who can do it for you.  Building omnipay gateways is not difficult, mostly it's cut-and-paste coding from other gateways.
