### ISSUE TITLE
Symfony 3

### ISSUE THREAD

**Issue by alanrivetta** [thephpleague/omnipay#420]
Hellow! 

Is it currently stable and deployable in Symfony 3?

**Comment by barryvdh** [comment]
No

**Comment by alanrivetta** [comment]
Is it okay, is there an estimated departure date?

Thank you very much!

**Comment by alanrivetta** [comment]
Is there any alternative for a stable development at the moment about Symfony 3?

**Comment by delatbabel** [comment]
This will happen with Omnipay 3.0.
