### ISSUE TITLE
Tests failing, Travis doesn't handle HHVM

### ISSUE THREAD

**Issue by delatbabel** [thephpleague/omnipay#438]
Just a reminder to myself that the tests are failing for no good reason -- Travis appears to no longer handle HHVM so we need to remove this from the Travis config file.  Hopefully I will get to this next week if nobody beats me to it.

**Comment by gries** [comment]
Hi, alternatively you could add:
```
dist: trusty
```
To the config to continue HHVM support if that's what you want.
src: https://github.com/travis-ci/travis-ci/issues/7712

**Comment by barryvdh** [comment]
REmoved

**Comment by delatbabel** [comment]
Muchas gracias, @barryvdh
