### ISSUE TITLE
returnUrl is not working

### ISSUE THREAD

**Issue by abdullahessam** [thephpleague/omnipay#453]
hello i have problem that when i click continue it's not redirect to returnUrl but it redirect to same page and there is no  Withdraw 
![image](https://user-images.githubusercontent.com/24545226/29099077-3729a690-7ca3-11e7-987c-9cec04e3020c.png)
this my code
![image](https://user-images.githubusercontent.com/24545226/29099088-55050ccc-7ca3-11e7-86b7-3ce53e96a84c.png)
please help

**Comment by fmp777** [comment]
I'm new to omnipay personally, but have you tried a public site with SSL enabled?  I would imagine paypal wouldn't enjoy a returnUrl of localhost and maybe not non-ssl as well

**Comment by makasim** [comment]
@fmp777 Paypal does not care about returnUrl. It has to be a valid url. Localhost is working just fine.

@abdullahessam I would it was something wrong at your side.

**Comment by abdullahessam** [comment]
when i used netshell same problem but when i change the route to /paypals/ it works !!! and i have no idea what happen or why

**Comment by delatbabel** [comment]
1. I believe this may have something to do with the set up of PayPal's IPNs.  The provided returnUrl may have to at least partially match one of those IPNs. Check the documentation.  This probably explains what @abdullahessam is seeing.
1. This is not an omnipay issue. It's a PayPal issue.
1. This is a bug tracker. It's not a support forum for omnipay or PayPal issues. The correct support forum for omnipay issues is StackOverflow. Use the the #omnipay tag.
