### ISSUE TITLE
Gateway for free (0.00) orders

### ISSUE THREAD

**Issue by colinodell** [thephpleague/omnipay#460]
Would there be any interest in including a dummy payment gateway that only accepts free (0.00) orders?  Currently, users need to add logic to bypass Omnipay if the order is free:

```php
if ($order->getGrandTotal() > 0) {
    $factory->getGateway($order)->purchase($foo);
} else {
    // Do something else
}
```

By providing a gateway that handles these orders, the logic becomes simplified:

```php
$factory->getGateway($order)->purchase($foo);
```

Some websites may offer different payment methods during checkout - in these cases, each option maps to a particular gateway, except for free orders - thus additional logic may be needed to handle the selection of a "Free" payment method differently.

While not everyone may choose this approach, I think it's common enough that providing a default gateway for free orders would be helpful for those who need it.

I have an implementation at https://github.com/colinodell/omnipay-zero that I'd be happy to transfer to the League (and possibly rename from `zero` to `free` to make it more clear what this does).

Just let me know!

**Comment by delatbabel** [comment]
Yes you can submit this although I don't believe that the league accepts transfers of packages any more.  The correct thing to do is to submit a PR for the README.md file in this package.

**Comment by colinodell** [comment]
Sure.  I've submitted 2 PRs: one for `README.md` and another for the website.
