### ISSUE TITLE
Discontinue Use of GET Method for Classic NVP/SOAP APIs

### ISSUE THREAD

**Issue by vishalpawar-tudip** [thephpleague/omnipay#472]
Hello Team,

We are using omnipay bundle for integrating PayPal express checkout which having API version 119.0.
As per the Paypal security update email, do we need to update the HTTP GET method to POST request method used with NVP APIs in this Bundle(omnipay/omnipay: 2.0)?

Please suggest the solution to it asap.
Any help is really appreciated.
Thanks.

**Comment by delatbabel** [comment]
The PayPal gateway does not use GET methods, it only uses POST methods.
