### ISSUE TITLE
build a driver for Omnipay

### ISSUE THREAD

**Issue by immeyti** [thephpleague/omnipay#473]
Hello,

I'm going to build a driver for Omnipay and use it in my project. I read the Omnipay Documentation, but i didn't understand it and generally, I don't know how to do it! I don't know where to start and what steps to take.

Thank you in advance

**Comment by barryvdh** [comment]
You can check https://github.com/thephpleague/omnipay-skeleton as a starting point, and look at stripe/paypal as reference implementations.
