### ISSUE TITLE
How to correctly handle completePurchase after redirect.

### ISSUE THREAD

**Issue by mungurs** [thephpleague/omnipay#479]
Hello!

I'm developing omnipay package for a banks gateway. In this gateway a simple purchase() -> redirect() flow happens and user gets redirected to gateways page. After user has successfully paid he is redirected back to merchants page with all the necessary data.

From my understanding this is the moment where completePurchase method could be called, but the problem is that gateway has completed the purchase already. I don't need to send anything to server, I only need to validate the response data and check if the status of the payment in data is successful. 

Because there are no further requests to be made, I made a completePurchase method that creates fake request class. In this class send() method does not send anything , it just creates response class with all the data that i received after redirect. This allows me to have a simple flow of completing purchases when multiple and different gateways are used.

Example:
```php
Omnipay::gateway($gatewayName);
$response= $gatewayObj->completePurchase($data)->send();
if ($response->isSuccessful()) {
    //paid
}
//failed
```

Is this the right way to do this? Can anyone suggest a better approach?

Sorry for my English!

**Comment by judgej** [comment]
Great English there - even if it wasn't, there is *no* need to apologise :-)

What you have described is spot-on. This is how I do it.

If the data the user has brought with them needs to be validated, such as checking a hash, then the `send()` method is a good place to do that, raising an exception if the checks fail. This would indicate the return data is corrupt or has been changed by a third party, so cannot be trusted. You can still log that data from the `$request->getData()` method for later analysis. This is why it is a good idea to split the line:

```php
$request = $gatewayObj->completePurchase($data);
try {
    $response = $request->send();
} catch {\Exception $e) {
    $dataToAnalyse = $request->getData();
}
```

You should not need to pass data into `completePurchase()`, as that object will have access to the HTTP client to get what it wants.

**Comment by mungurs** [comment]
Thank you for guidance!
