### ISSUE TITLE
Request: Installment Plan Gateways

### ISSUE THREAD

**Issue by tmikaeld** [thephpleague/omnipay#481]
Over 70% of Orders in the Nordic is now handled by Klarna, due to their "Buy now pay later" method.

[Klarna PHP SDK](https://developers.klarna.com/en/se/kco-v2/download/php)

And [Payolution](https://www.payolution.com/) is growing in Germany and UK.

DiBS also has a [similar system](https://tech.dibspayment.com/easy).

As far as i can tell, These types of payment require adding a new field (Personal Identity Number) and also polling JSON for the payment plans (Klarna & Payolution).

Would this be possible to add? If it is, then i can look at adding these to Omnipay.

**Comment by barryvdh** [comment]
The field can be added to the gateway parameters, just like any parameter. You can also implement other requests to get the payment plans.
