### ISSUE TITLE
Spreedly Gateway

### ISSUE THREAD

**Issue by gregoriohc** [thephpleague/omnipay#486]
Hi!

I just wanted to let you know that I have implemented the Spreedly gateway for Omnipay:
https://github.com/gregoriohc/omnipay-spreedly
Spreedly is a payment gateway aggregator (like Omnipay but SAAS :stuck_out_tongue_winking_eye:).
Currently the library supports the basic Omnipay methods (authorize, purchase, capture, refund, void) and some more.
I guess that Omnipay is not accepting transfers of packages anymore, so I would try to maintain this package if enough people is interested.

Regards!

**Comment by barryvdh** [comment]
Thank you, can you submit a PR to add it to the list?

**Comment by gregoriohc** [comment]
@barryvdh Done! ;-)
