### ISSUE TITLE
Update on v3?

### ISSUE THREAD

**Issue by karlmonson** [thephpleague/omnipay#487]
Is there any traction or timeline for v3? I would love to use this in my Laravel 5.6 project.

**Comment by jblotus** [comment]
same

**Comment by davidbankes** [comment]
The roadmap on the omnipay-common package seems to show what remains. There has been some recent movement.

https://github.com/thephpleague/omnipay-common/issues/146

**Comment by barryvdh** [comment]
Yeah I've tagged some alphas. Progress in the related issue.
