### ISSUE TITLE
Returning empty response from the server while using PayPal Express Checkout.

### ISSUE THREAD

**Issue by vishalpawar-tudip** [thephpleague/omnipay#489]
Hello Team,

I am using Express Checkout in sandbox mode(TestMode = True) but it gives me an exception 
Like below:
`"Curl Exception: Empty Reply From Server URL: https://api-3t.sandbox.paypal.com/nvpVERSION=119.0&USER=*****&PWD=****&SIGNATURE=****METHOD=SetExpressCheckout&PAYMENTREQUEST_0_PAYMENTACTION=***&PAYMENTREQUEST_0_CURRENCYCODE=USD&PAYMENTREQUEST_0_INVNUM=***&PAYMENTREQUEST_0_DESC=****&SOLUTIONTYPE=
`
It works perfectly in the production environment.

My code is like:

     `  $gateway = Omnipay::create('PayPal_Express');
        $gateway->setUsername($this->_parameters['paypal.username']);
        $gateway->setPassword($this->_parameters['paypal.password']);
        $gateway->setSignature($this->_parameters['paypal.signature']);
        $gateway->setTestMode(true);
        $params = array(
            'amount' => round($cart->getCart()->total(),2),
            'description' => "ABC - ".$cart->getSlug(),
            'currency' => 'USD',
            'transactionId' => $cart->getSlug(),
            'returnUrl' => $this->_router->generate('paypal_complete', array('slug' => $cart->getSlug()), true),
            'cancelUrl' => $this->_router->generate('paypal_cancel', array(), true),
            'clientIp' => $_SERVER['SERVER_ADDR'],
            'handlingAmount' => round($cart->getCart()->TotalFees(),2)
        );

        $items = array();

        foreach ($cart->getCart()->getItems() as $cartItem) {
            $items[] = array('name' => $cartItem->get('name'),
                             'description' => $cartItem->get('description'),
                             'quantity' => $cartItem->get('quantity'),
                             'price' => $cartItem->getSinglePrice(), );
        }

        if (count($cart->getCart()->getCoupons())>0) {
            $items[] = array('name' => "Discount",
                'quantity' => 1,
                'price' => $cart->getCart()->totalDiscounts(), );
        }

        $response = $gateway->purchase($params)
            ->setItems($items)
            ->send();

        if ($response->isRedirect()) {
            $response->redirect();
        } else {
            echo $response->getMessage();
        }
    }`
 
Any help is really appreciated!!

**Comment by delatbabel** [comment]
This is probably the wrong place to raise this issue because it's not a generic omnipay issue. You should raise the issue in the gateway itself (omnipay-paypal) or if it's a support request use StackOverflow. It's probably worth checking the dashboard on the paypal side to see if anything shows up there. The code looks OK to me and I know this is working for other people (as you say it's working in production) so maybe there's a key / signature issue.

**Comment by vishalpawar-tudip** [comment]
Thanks for the update @delatbabel 
I will look into the key/signature and let you know as soon as possible.
