### ISSUE TITLE
PHP 7.2 support?

### ISSUE THREAD

**Issue by FlorianFranzen** [thephpleague/omnipay#492]
The composer.json of the latest beta still requires version 7.1. 

It seems however that the latest builds mostly tests fine with PHP 7,2:
https://travis-ci.org/thephpleague/omnipay-common/jobs/359433967

When will omnipay officially support PHP 7.2?

**Comment by barryvdh** [comment]
What do you mean? It requires `^7.1` which allows all php 7 version >= 7.1?

**Comment by FlorianFranzen** [comment]
Weird and to long a go to still triage. Must have been on an old version. Thank you any way.
