### ISSUE TITLE
Get payment status method

### ISSUE THREAD

**Issue by DrRoach** [thephpleague/omnipay#523]
Hi,

It would be really useful to have a method that returns the method of the payment for each gateway.

For example, if a payment is set as `Authorised` this should be reflected along with when it is set to `Captured`. There's at least one gateway (Worldpay Business) where captured payments aren't instantly captured and take time, ~15 minutes, for the payment to change from `Authorised` to `Captured`.

This means that if the payment is cancelled in the above timeframe, there's no way to know that this has happened and this is treated as a successful payment even if that is not the case.

**Comment by judgej** [comment]
If the initial returned status is authorizied, then that is what the gateway driver should return as a status. There will be webhooks that provide updates on that status. I think (at this time at least) it is up to the merchant application to keep track of those changes.

If the sequence of events can be described in a generic and flexible enough way to cover all the gateways, then perhaps a proposal can be made?

**Comment by DrRoach** [comment]
While I'm not 100% sure what I was talking about exactly, I think that I was talking about some form of `getPaymentStatus()` method that would return the corresponding status. I know that this wouldn't be possible to do in the parent Omnipay package but could it be added as part of the guidelines for individual gateway drivers?
