### ISSUE TITLE
PHP Parse error

### ISSUE THREAD

**Issue by cloudinstone** [thephpleague/omnipay#530]
PHP Parse error: syntax error, unexpected 'function' (T_FUNCTION), expecting identifier (T_STRING) or \\ (T_NS_SEPARATOR) in /home/public_html/github.com/fake-path/vendor/omnipay/common/src/Common/Http/Client.php on line 5

**Server Information**
Apache Version | 2.4.34
PHP Version | 5.6.37
MySQL Version | 5.6.40
Architecture | x86_64
Operating System | linux
Path to Sendmail | /usr/sbin/sendmail
Path to Perl | /usr/bin/perl
Perl Version | 5.10.1
Kernel Version | 2.6.32-896.16.1.lve1.4.54.el6.x86_64

**Comment by judgej** [comment]
Which version of PHP are you using? This [should work from PHP 5.6](https://stackoverflow.com/a/20933938/218208).

The line in error is:

https://github.com/thephpleague/omnipay-common/blob/master/src/Common/Http/Client.php#L5

**Comment by cloudinstone** [comment]
@judgej I test it on a shared Hosting by Fastcomet, the cPanel said it's 5.6.37. it's working on my local env.
