### ISSUE TITLE
Send a POST request as application/x-www-form-urlencoded

### ISSUE THREAD

**Issue by sheriffmarley** [thephpleague/omnipay#565]
How are you supposed to do a request like:

```php
 $client = new \GuzzleHttp\ClientClient();
            $response = $client->post($this->endpoint, [
                'form_params' => $data
            ]);
```
in omnipay? 

I took a look in mostly every package for omnipay^3 but i just came up with this line of code.
```php
$this->httpClient->request('POST', $this->endpoint, [], http_build_query($data))
```
it's not send as application/x-www-form-urlencoded .

I tried to pass it in the header parameter, but yeah that is obvious that it won't work.

So how can you send a post request with `form_params`

**Comment by judgej** [comment]
The third parameter is where you add the headers. Check out this example:

https://github.com/thephpleague/omnipay-sagepay/blob/master/src/Message/AbstractRequest.php#L200

**Comment by sheriffmarley** [comment]
Thanks worked! :)
