### ISSUE TITLE
I want to implement NganLuong v3 for omnipay v3. 

### ISSUE THREAD

**Issue by xblue55** [thephpleague/omnipay#604]
- I integrate NganLuong v3 completed  for omnipay v3. but i cant register packagist with name ominipay/nganluongv3. how i can do that.
- https://www.nganluong.vn/vn/integrate/seamless.html

**Comment by barryvdh** [comment]
Register it under your own namespace please.

**Comment by xblue55** [comment]
Thanks for you infomation.
