### ISSUE TITLE
Installation does not work using PHP 8

### ISSUE THREAD

**Issue by pierreminiggio** [thephpleague/omnipay#637]
Hello. I can't install omnipay on PHP 8.
![image](https://user-images.githubusercontent.com/35456349/110313645-0744ae00-8007-11eb-8356-cae48b28087b.png)

Tried setting my omnipay dependency to the dev-master branch as I noticed PHP 8 support is supposed to be handled by this PR that got merged on master : https://github.com/thephpleague/omnipay/pull/625

But as you see it does not work, because the omnipay/common dependency's version stated in omnipay composer only supports PHP7.

I can still use the ignore-platform-reqs flag of composer to install it, But gotta say I don't like doing that :'(

**Comment by pierreminiggio** [comment]
I'm having a similar issue with omnipay-stripe : https://github.com/thephpleague/omnipay-stripe/issues/198

**Comment by Ocramius** [comment]
This is expected: mostly need a release to be tagged, but otherwise `dev-master` is already capable of being installed with PHP 8

**Comment by bbashy** [comment]
Been tagged by the looks of it.

**Comment by barryvdh** [comment]
Yes it's tagged 🎉

**Comment by pierreminiggio** [comment]
Hello ! Thanks, I'm confirming that it now works on my PHP8 project without needing to use the ignore-platform-reqs option.
