### ISSUE TITLE
Amazon payment

### ISSUE THREAD

**Issue by danielplatt-clx** [thephpleague/omnipay#645]
Hello,

we are currently searching for a way to implement amazon payment with omnipay. Is there a current version of a api? I only found `lemonstand/omnipay-amazon`, which hasn't been updated since 6 years. It seems that is doesn't contain any functionality yet.

Greetings and thank you

Daniel

**Comment by barryvdh** [comment]
I'm not sure. We maintain a list on the readme, but otherwise you can search Packagist.
