### ISSUE TITLE
Support FCQN for GatewayFactory

### ISSUE THREAD

**Issue by Mouke** [thephpleague/omnipay#650]
Hello there !

I'm testing Omnipay for the first time and I'd like to suggest an enhancement. After a small search in issues, i've seen no traces of such suggestion.

Currently, to use Omnipay/Stripe's PaymentIntents Gateway, I have to write this code : 
`$gateway = Omnipay\Omnipay::create('Stripe\PaymentIntents');`

Why not allow to use the gateway FQCN in \Omnipay\Common\Helper::getGatewayClassName ? It would be much easier (and cleaner) to write this :
`
use Omnipay\Stripe\PaymentIntentsGateway;
$gateway = Omnipay\Omnipay::create(PaymentIntentsGateway::class);
`

If you want, I would gladly make that small update and suggest a PR for that.

**Comment by barryvdh** [comment]
isn't this already possible?

**Comment by Mouke** [comment]
I tried yesterday (I don't have my code under the nose so I can't give you my composer.lock exact version but it should be the latest one), it doesn't work.

When I tried to give it the FQCN, it tried to load `Omnipay\Omnipay\Stripe\PaymentIntentsGateway\Gateway`

**Comment by barryvdh** [comment]
Ah yes, see https://github.com/thephpleague/omnipay-common/blob/5b16387ec5ab1b9ff86bdf0f20415088693b9948/src/Common/Helper.php#L128

Yeah I think the problem was that classes can exists (eg '\Stripe'). But we could use https://www.php.net/manual/en/function.is-subclass-of.php to check if the full name is actually a class that implements the gateway interface.

**Comment by barryvdh** [comment]
If you could make a testcase for it, that would be great!

**Comment by Mouke** [comment]
I'll try to send you a PR with the fix and a testcase this week.

**Comment by Mouke** [comment]
It is very weird : If I use '\\Omnipay\\Stripe\\PaymentIntentsGateway' it works, but if I uses PaymentIntentsGateway::class (which prints '\Omnipay\Stripe\PaymentIntentsGateway'), it doesn't.

**Comment by barryvdh** [comment]
yeah it checks on `\` so need to change it.

**Comment by Mouke** [comment]
I'm adding a check if it starts by Omnipay\. Will do the job.

**Comment by barryvdh** [comment]
THanks. TWeaked it a bit: https://github.com/thephpleague/omnipay-common/commit/30c6db3e9c2df34c2c9ad854b8bca53b597b456a

**Comment by Mouke** [comment]
Thanks for your reactivity :)
