### ISSUE TITLE
Klarna Community gateway seems dead

### ISSUE THREAD

**Issue by chrillep** [thephpleague/omnipay#667]
https://github.com/thephpleague/omnipay/blob/master/README.md?plain=1#L179

https://github.com/MyOnlineStore/omnipay-klarna-checkout/issues/72#issuecomment-980680354

it only supports php 7

https://github.com/MyOnlineStore/omnipay-klarna-checkout/blob/master/composer.json#L15

what to do ?
Maybe remove it from the list?

**Comment by barryvdh** [comment]
We can add this to the list perhaps; https://github.com/dalholm/omnipay-klarna

**Comment by chrillep** [comment]
yeah unless they respond it would be better :)

**Comment by chrillep** [comment]
@fred-jan @frankverhoeven @Feijs seem to have fixed this now in
https://github.com/MyOnlineStore/omnipay-klarna-checkout/releases/tag/4.0
