### ISSUE TITLE
Mobile Purchase

### ISSUE THREAD

**Issue by mrzepinski** [thephpleague/omnipay#74]
Is there any chance to get mobile purchase solution?

I mean implementing https://developer.apple.com/in-app-purchase/ and http://developer.android.com/google/play/billing/billing_overview.html payment methods that store, verify receipts for mobile devices.

**Comment by weismannweb** [comment]
This has to be supported by each pay method.  Which it is these days especially if you use the javascript token method of displaying the payment form.  Can I ask if apple pay, google pay is working for auth.net, paypal, or braintree with this module?
